sudo: false
language: java
install: true
cache:
  directories:
  - "$HOME/.m2"
before_install:
- "./scripts/status-checks.sh verify"
script:
- "./scripts/status-checks.sh test"
- "./scripts/status-checks.sh coverage"
after_success: 
env:
  global:
    secure: O9D2aJzvZGO2nt2/TUEdNpbt1yiIs6XVwrDubMiYFAAIG6aVVkw159H0RsR2xFQ4tFV9Wjd84PJDNy03xb+sLrq2inD1iHhin8GUv4uvhJGru7JHAIhpeGEuE48x4+jWBpAdK8mIxmyCN5sYqTLculCH+5lyi7ABfr7mCo6MGtZll7nBFFgZ+gvw25gIQ00hN1Prd/c3xXqvtp/pb8NHPtA+L8YJQYAr5vs3Zo9rQv0kRXfStzr/3VieNlyNi8QNS5UQvwYBG3gk1MqvP/CMurwHCjoQ3YVIF0QV3+FjmrN2QWnn3uo2z+sWCmPVraabwhjz04R/SNMHltG2Ed7tl+P3uLLT+LzF9oxn2pONTi3UZwZI8UuVD/NtptONey5+hoGc6wXzEMCZq+DoGzQViT7RWRaHM1HLY4+0QmnCPbXnufZf2gcEjvuWlSQJrX2OadLLwdb6DuYSDxINRwR0hm1HoxM3C0+aOZ4fdfnB5rJM9BxXl6fSbJPvktPQnTeu/LJ1gCFf0UWY+wDTJnEkCN7sMEGi1xj/mFh6nmmYGW7mUPQfRu8NyL+WqUZDsN7o4OHBBMUdAK4QRUQBWwwXAepafWxQ9fk/15YoJiicAADg9dBqyOFRXyriW/m+Q+WTWfTo/EMD1U5yV1nh2bJZpuwBiVR25fBp5A66wJ0FGIw=
