sudo: false
language: java
install: true
cache:
  directories:
  - "$HOME/.m2"
before_install:
- "./scripts/status-checks.sh verify"
script:
- "./scripts/status-checks.sh test"
- "./scripts/status-checks.sh coverage"
after_success: 
env:
  global:
    secure: BnB5ZQ+GZjT+y2pRc+ssQTNqfcnGye9OgAbiUlCE222pSVXVGGvBBKM2KJtkVPuFzsuD1xfui01cahceMR1aLK2c19Blf6791CHNchT5gBQ2F86mQd1/2qFHi9/boMH93Xcpa3qyMcQvbqGWtee9b6RAqaa1n29ZT2PYe46QtwE+OffOeu983G51oKfdpC7xio0q3jKwv+b5GzT8WhLcj//fCF0anRQoDFpNhWKvjKGl480KBEqQADr/lXJw5PVipK67mPvCuzq1L3iML17QQC86kqZRnpbqPmQLG8dnyiYRVL+IPf9HL/mxzxLWdxDFdmbgWzjI22RmdLFf9Ny8nrpuJZRspNDpXoMCikn70cMchQ65krZImxuQ1sGxeBNZD2t7bdr4I+A1w543svAAsQ5WMGKH+K0+4019cTBZ1hHzm5kWKjmGNj65nb+6XpivSdvPQYy6nLO0TtqThrfVdtVSAlO0y5AEgH9Q71Svl3E5mo0zjQhrwDn+AX2T07SWvlxNwyDaLIPXA5zl3uMZAiiW9DpQORFtedC0rmhCUUvAMSRGZ8/EUjSS9zoZFSHgV7ns348nUwgrQQcU+ZzFitYDYcb9PsB280+jF7Su+rQGhqjwx9QQsCZrsATFnjpez0SK2Xei+naML7FvV9IGzAOeDq5pGhFJUpU7XIJwZ7c=
